FROM vs/domino:9.0.1-fp7

# Set the init service as entrypoint to have domino start with the image
#ENTRYPOINT exec /etc/init.d/rc_domino monitor
#ENTRYPOINT su - notes -c "cd /local/notesdata; /opt/ibm/domino/bin/server"
EXPOSE 25 80 443 1352 8585

COPY resources/serversetup/* /local/notesdata/
COPY resources/docker-entrypoint.sh /usr/local/bin/
RUN ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat
ENTRYPOINT ["/docker-entrypoint.sh"]

# Perform silent configuration of the server based on recorded profile
#RUN su notes -c "cd /local/notesdata && /opt/ibm/domino/bin/server -silent /local/notesdata/Main_Server.pds"

VOLUME ["/local/notesdata"]
