FROM vs/domino:9.0.1

ENV DOM_PKG=resources/domino_901_fp7
ENV DOM_CONF=resources/serverconfig

COPY ${DOM_PKG}/ /tmp/sw-repo/
COPY ${DOM_CONF}/ /tmp/sw-repo/serverconfig

ENV NUI_NOTESDIR /opt/ibm/domino/
RUN cd /tmp/sw-repo/domino && bash -c "./install -script /tmp/sw-repo/serverconfig/domino901_fp7_response.dat"

RUN rm -rf /tmp/*